name: Deploy

on: workflow_dispatch

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: self-hosted
    steps:
      - name: Delete old ajor-debtor-bot container
        run: docker stop ajor-debtor-bot && docker rm -f ajor-debtor-bot
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run and pull new image
        run: |
          docker run -d --name ajor-debtor-bot \
          --restart always \
          -e TELEGRAM_BOT_DEBUG_MODE=${{ secrets.TELEGRAM_BOT_DEBUG_MODE }} \
          -e TELEGRAM_BOT_ADMIN_ID=${{ secrets.TELEGRAM_BOT_ADMIN_ID }} \
          -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
          -e XPANEL_URL=${{ secrets.XPANEL_URL }} \
          -e XPANEL_USERNAME=${{ secrets.XPANEL_USERNAME }} \
          -e XPANEL_PASSWORD=${{ secrets.XPANEL_PASSWORD }} \
          -e APP_LOG_MODE=${{ secrets.APP_LOG_MODE }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:{{ vars.APP_VERSION }}
